"""add_floor_plans_table

Revision ID: 6bcd08b685f1
Revises: 
Create Date: 2025-11-13 10:53:03.805428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcd08b685f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('layout_data', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floor_plans_id'), 'floor_plans', ['id'], unique=False)
    op.create_index(op.f('ix_floor_plans_location'), 'floor_plans', ['location'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_floor_plans_location'), table_name='floor_plans')
    op.drop_index(op.f('ix_floor_plans_id'), table_name='floor_plans')
    op.drop_table('floor_plans')
    # ### end Alembic commands ###
